apply plugin: 'com.android.library'

android {
    namespace 'com.parrot.arsdk.arutils'
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['JNI/java', 'gen/JNI/java']
        }
    }
}

dependencies {
    api project(':libARDiscovery')
    api project(':libARNetworkAL')
    api project(':libmux')
    api project(':libARSAL')
}
